### ISSUE TITLE
Themes are reset when the 3DS restarts

### ISSUE THREAD

**Issue by mikesierra85** [RocketRobz/3DSBank#2]
I have noticed that themes always get reset to the default one upon restarting the handheld. Also, Anemone3DS themes don't work.. Could you please confirm if this is a known issue? I have about 5 or 6 banks.

Anemone3DS themes work fine on my other 3DS that isn't running 3DSBank. Both SD cards were formatted using a 32KB cluster size.

Thank you.

**Comment by RocketRobz** [comment]
This doesn't sound like a 3DSBank issue, though idk why this happens.
