### ISSUE TITLE
Downloaded CIA file not appearing on Home Menu

### ISSUE THREAD

**Issue by tknittel** [RocketRobz/3DSBank#3]
So I want to download 3DSBank. I went and downloaded the .cia file and put it onto my 3ds SD card. I put the sd card into my console, launched FBI, and downloaded the 3dsbank cia. However, the application doesn't appear on my home menu. I know about the 300 game limit, and I have plenty of room for more applications. Can you help?

**Comment by RocketRobz** [comment]
Close and open the console's lid, or reboot the console for 3DSBank to appear.

**Comment by tknittel** [comment]
It still didn't appear even after closing/reopening the lid, and rebooting the console

**Comment by DraconicNEO** [comment]
How many Dsiware do you have, there's a 40 title limit for DSi software.
