### ISSUE TITLE
Any way to have FBI app and universal updater etc copy over to new folders?

### ISSUE THREAD

**Issue by Jbe1091** [RocketRobz/3DSBank#5]
Just wondering if there's any way to copy over the .Cia files or the installed files of FBI, Universal Updater, etc. Needed to install homebrew and games to each folder created through your app or possibly through the GM9 menu?

**Comment by Jbe1091** [comment]
Like how can I install games or anything if I don't have access to the apps necessary to do so? Any help is appreciated.

**Comment by RocketRobz** [comment]
You can start the Homebrew Launcher using the Luma feature where launching a 3DS title brings you to HBL.
You can then start FBI from there.

That said, there is no way to copy installed titles between `Nintendo 3DS` folders.
