### ISSUE TITLE
3ds bank stuck on white screen

### ISSUE THREAD

**Issue by GradyGrizz** [RocketRobz/3DSBank#9]
I opened my second folder on my 3ds bank and then renamed them in the sd card. Now when I try to switch back to my main home folder, it just gets stuck on a white screen and I have to power off to go back to the second folder. Now there's no way for me to go back to my main 3ds folder.

**Comment by GradyGrizz** [comment]
fml i didnt have the sd card all the way in

**Comment by RocketRobz** [comment]
I assume your issue is fixed then. Closing.
